sighmon/mjml-rails

lib/mjml/railtie.rb
Avoid overriding the existing text/html MIME type by registering the MJML type as an alias.
This should address the issues brought up in #5, and also resolves an issue I've had with an uptime monitoring servicing making requests with an `Accept: text/html` header causing 500 errors in the application due to a "missing template":
> ActionView::MissingTemplate
> Missing template home/index, application/index with {:locale=>[:en], :formats=>[:mjml], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :haml, :mjml]}.
=> Register the MIME type as an alias

lib/mjml.rb
Hey guys.
With this little change developers may specify in any config file (for ex. config/initializers/mjml.rb) templating language they are using, and it should work properly basically for all available templating languages.
Config file should look like this:
```ruby
Mjml.setup do |config|
config.template_language = :slim # :erb (default), :haml, or any other you are using
end
```
Hope this little change proves to be useful, if you have any ideas to improve this do not hesitate to let me know or update the PR 😄 It kind of solves #3 :wink:
I was looking for better solution, so developer just had to add .slim, or .haml extension to .mjml file, without having config file, but wasn't able to make it work - if anyone has any idea I would be happy to collaborate on this.
For syntax …
=> Allow developer to specify templating language they use

lib/mjml.rb
When the `mjml` command isn't in the path, error output such as the following will be seen:
```
./bin/rake: No such file or directory - mjml
```
This changes `.check_version` to use `IO.popen` instead so an error will be raised in this case (which is caught by `rescue`, so the method still returns `false`).
=> Silence output when mjml binary isn't in path

lib/mjml.rb, lib/mjml/parser.rb
This allows to run a `rake yarn:install` in Rails 5.1 to actually install mjml.
Since rake tasks run through Rails now, it errors out otherwise and
prevents a successful deploy.
`rake yarn:install` is run before `assets:precompile` automatically in
Rails 5.1.
=> Only raise when really using mjml if binary is not found

lib/mjml.rb
Because I'm using webpacker, npm isn't installed, but yarn is.
Because npm isn't installed, pushing to heroku fails.
=> Let it work with yarn as well as npm on heroku

Gemfile, Gemfile.lock, lib/mjml.rb, lib/mjml/parser.rb, test/parser_test.rb, test/test_helper.rb
* Current implementation of swallowing error in `Mjml::Parse#render` method is dangerous. Particularly, it does not only produce confusing result, but also make it difficult to debug.
* Add exception raising configuration for Mjml::Parse#render method:
```ruby
Mjml.setup do |config|
config.raise_render_exception = true
end
```
=> Add render exception config

lib/mjml.rb
Hi 👋 
first of all: **thanx a ton for building an maintaining this gem 💚** It's really helpful 🤗 
This PR fixes the check for the `mjml` version to clean up after itself and not leave a `node` zombie process lingering around 🧟‍♂️
We're using `Sidekiq` to send emails in background jobs and our workers always had some _"defunct"_ node processes lingering around forever - even directly after starting / restarting Sidekiq.
This line in `mjml.rb` 👇 
```ruby
IO.popen("#{bin} --version").read.include?('mjml-core: 4.0.')
```
This runs `mjml --version` as a subprocess. But since the IO object is never closed, the process never gets terminated.
Looking at the [docs for IO#popen](https://ruby-doc.org/core-2.5.0/IO.html#method-c-popen), the method can also take a block, like so:
```ruby …
```
=> Fix version check to clean up after itself 👮‍♀️

lib/mjml/parser.rb, test/parser_test.rb
* `Mjml::Parse#run` swallows shell execution error by using backtick syntax. Causing failure for subsequence instructions.
* Use `Open3.popen3` to support error raising for `Mjml::Parse#run` method.
=> Replace backtick with Open3 for parser

Gemfile.lock, README.md, lib/mjml.rb, lib/mjml/parser.rb, lib/mjml/version.rb, test/parser_test.rb, test/template_test.rb, test/views/notifier/contact.mjml, test/views/notifier/no_partial.mjml, test/views/notifier/user.mjml, test/views/template_subdir/simple.mjml, test/views/template_subdir/simple_block_and_path.mjml, test/views/template_subdir/simple_with_path.mjml
Installing `mjml@4.0.3` is currently pulling in `miml-core: 4.1.0` so the version checking wasn't working anymore.
I also:
* Removed references to `<mj-container>` to get tests passing again
* Switched to using `Tempfile` in `parser.rb` after I had some filename conflicts.
=> mjml 4.1.0 support 

README.md, lib/mjml.rb, test/views/no_layout_mailer/inform_contact.mjml
Expanded MJML root tag `<mjml owa="desktop">` results in message not rendering to HTML.
=> Expanded MJML root tag breaks rendering

README.md
The current example of formatting in the readme will cause some clients (such as gmail) to only display the text version. The enhanced html version should always be last.
From the Multipart RFC 1341 spec:
> In general, user agents that compose multipart/alternative entities should place the body parts in increasing order of preference, that is, with the preferred format last. For fancy text, the sending user agent should put the plainest format first and the richest format last.
=> swap order of mjml/text in format block

lib/mjml.rb
To better support paths with spaces and other characters that need escaping, use the array form of `IO.popen`'s `cmd` argument which will handle escaping for us.
=> Escape path when checking MJML binary version

.travis.yml, CHANGELOG.md, lib/mjml.rb
This pull requests fixes discovery of the `mjml` binary, when there is only yarn (but no npm) installed.
In case a binary called through backticks is missing, ruby will raise `Errno::ENOENT`.
Thus the previous code failed to discover the bin path, when npm
was not present on the system, because an error was raised immediately.
On a system that has `yarn` installed, but no `npm` (e.g. in a docker image) try booting your Rails application. Prior this PR, it should error out:
```
$ be rake -T
rake aborted!
Errno::ENOENT: No such file or directory - npm
/home/jan/development/hub/myapp/config/application.rb:20:in `<top (required)>'
/home/jan/development/hub/myapp/Rakefile:3:in `require'
/home/jan/development/hub/myapp/Rakefile:3:in `<top (required)>'
```
=> Fix discovering mjml binary when npm is missing

lib/mjml.rb
The fix introduced in https://github.com/sighmon/mjml-rails/commit/f05d2bf2e06aa1251ee0a6c7c45dd4f987090722 is not working for me when npm is not installed. 
`` `npm bin` `` returns `nil` instead of throwing an exception, so we get a `NoMethodError` on `chomp` . This seems to be caused by rails overriding backticks: https://github.com/rails/rails/blob/v5.1.4/activesupport/lib/active_support/core_ext/kernel/agnostics.rb
This PR uses `Open3` instead to find the bin path.
=> Use Open3 instead of backticks

README.md, lib/mjml.rb, lib/mjml/parser.rb, test/parser_test.rb
This is my try to make binary detection better and more error prone:
refactor detection of binary and unify executing mjml
- detect local first, then global
- use `yarn run` if installed with yarn, makes it work with yarn v2
- only use bin path when installed with npm, yarn should always work
with `yarn run`
- always execute mjml in the same way, whether when checking version or
transforming mail
This should fix #55.
Second commit:
always use full paths for binaries
Should fix #63
=> Refactor discovery of binary

README.md, lib/mjml.rb, lib/mjml/parser.rb, test/mjml_test.rb, test/parser_test.rb, test/test_helper.rb, test/views/notifier_mailer/invalid_template.html.erb
**Note**: This is based on top of #71. Please first look at #71, so hopefully #71 can be merged and then there will be fewer changes here. Then you can take a look at this one.
**Second note**: If this is merged and released, there should be a major version bump (I'd say `4.5`) with a changelog entry, because it is a possible backwards incompatible change if somebody has:
- manually set validation level to `soft` (e.g. is not using the default config) and
- relies on MJML-Rails raising an error on any template error, which it wouldn't do then anymore
---
Before this commit MJML-Rails *always* raised an exception if there is any
template validation error.
In MJML there are [two validation levels](https://github.com/mjmlio/mjml/tree/master/packages/mjml-validator#validating-mjml) though …
=> Change default validation level to `strict` and honor `validation_level`

.gitignore, test/mjml_test.rb, test/test_helper.rb
Resolves #86 
1. Run tests: `rake test`
=> #86 Fix tests

README.md
It's not so about the name itself (which isn't hard to guess is incorrect), as about the `.html.mjml` extension - I realized that `.html` should be removed only after reading the post linked below in the README. Until then I was receiving
=> Fix name of the example email template

lib/mjml/parser.rb, test/parser_test.rb
=> `ParseError` in `Mjml::Parser#run` includes the process status for debugging purposes.

README.md, lib/mjml.rb
Instead of running the bin through yarn (`yarn run mjml`), it makes it work like npm which is a faster way.
=> Stop running mjml with yarn. Instead fetch the bin

.github/workflows/test.yml
Resolves #101
1. Drops support for [Ruby versions < 2.7](https://endoflife.date/ruby)
1. Drops support for [Rails versions < 6.1](https://endoflife.date/rails)
=> #101 Update GitHub actions

lib/mjml.rb
Fix: #104
As explained in #104, the behavior of `yarn bin` has changed since yarn 2. Also, the `npm bin` command has been removed since npm 9.
This PR has been modified to support the new versions of yarn and npm as follows.
For yarn, the `yarn bin mjml` command outputs the full path to the mjml binary, so use that.
However, npm does not have such a command, and `npx` and `npm` exec have more overhead than executing the binary directly.
So I used the `npm root` command to get the full path of the local node_modules and appended the `.bin` directory. This is the same path as the result of executing `npm bin`.
Also, the `npm root` command works with npm 6~9.
Refs:
https://docs.npmjs.com/cli/v9/commands/npm-root
https://docs.npmjs.com/cli/v9/configuring-npm/folders?v=true#executables
And I …
=> Support for JS Package Manager updates

README.md, lib/mjml.rb, lib/mjml/handler.rb, lib/mjml/mrml_parser.rb, lib/mjml/parser.rb, mjml-rails.gemspec, test/mrml_parser_test.rb, test/test_helper.rb
This proof of concept change would allow using Rust implementation of MJML called MRML via the mrml-ruby gem. 
The benefits:
- no need for JS runtime in production to compile email templates
- MRML boasts better performance and lower memory usage
- MRML-ruby gem comes with precompiled binaries for all architectures so much easier to set up
- no need to write to temp files to feed input into MJML
Would anyone except me find this useful?
References:
- ruby gem: https://github.com/hardpixel/mrml-ruby
- MRML: https://github.com/jdrouet/mrml
MRML[ isn't 100% compatible](https://github.com/jdrouet/mrml#missing-implementations) with MJML, so I made it optional.
=> Allow using MRML via MRML-ruby

lib/mjml.rb, test/mjml_test.rb
Resolves #117 
1. Uninstall/remove `mjml` from your environment
1. Clone and switch to using this branch in your Gemfile: `gem 'mjml-rails', path: '../mjml-rails/'`
1. Add `config.use_mrml = true` to your initializer
1. Add `mrml` to your Gemfile
1. Note the warning of a missing MJML binary no longer occurs
=> #117 Warning about MJML missing when using MRML

README.md
The README's "How to guides" section refers to Kitty Giraudel by their deadname. This PR updates the README to use the name that the author identifies with. (See: https://en.wikipedia.org/wiki/Deadnaming)
=> Remove deadname from README.md

README.md, lib/mjml.rb, test/mjml_test.rb
My team and I recently started using [Bun](https://bun.sh/) instead of Yarn/NPM to manage JavaScript packages. The switch was quite painless, but our deploy to Heroku failed with the following error:
```
ActionView::Template::Error: Couldn't find the MJML 4. binary.. have you run $ npm install mjml? 
11  # @param input [String] The string to transform in html
12  def initialize(input)
13    raise Mjml.mjml_binary_error_string unless Mjml.valid_mjml_binary
14
15    @input = input
```
After some digging, I realized that we [specifically check for MJML in each given package manager](https://github.com/sighmon/mjml-rails/blob/master/lib/mjml.rb#L49-L54):
```rb
def self.valid_mjml_binary
self.valid_mjml_binary = @@valid_mjml_binary ||
check_for_custom_mjml_binary ||
check_for_yarn_mjml_binary …
```
=> Add support for the Bun package manager

lib/mjml.rb, test/fixtures/valid-mjml-binary/empty-path/which, test/mjml_test.rb
On a NixOS machine I was getting a message like the following on every Rails boot:
> which: no bun in (... [my path] ...)
I chased it down to this library's usage of `which` to find the mjml binary. Using backticks to call it meant stderr was passing through to the terminal.
Ubuntu and MacOS use different versions of `which` that do not print to stderr, so it's likely not many people have run into this issue.
=> Fix stray stderr output on machines with GNU which

.github/workflows/test.yml, .rubocop.yml, lib/mjml.rb, test/mjml_test.rb
Why:
Bun is a drop-in replacement for Node.js and does not rely on Node.js. In other words: You should be able use bun without any node installation in your system.
MJML js bin file has a shebang comment to rely on node. If bun encounters a shebang comment like this is it will either spawn a node process (https://bun.sh/docs/cli/run#bun) or it has fallback to a node cli wrapper script (AFAIK).
The current mjml-rails implementation does not rely on the bun cli command, instead it just searches the bun installed bin and runs it. This will fail if node is not installed on the system.
e.g.:
```
$ bun add mjml@^4.15.3 # installed mjml@4.15.3 with binaries: - mjml
$ bun pm bin #/Users/mjml-fan/mjml-rails/node_modules/.bin
$ /Users/mjml-fan/mjml-rails/node_modules/.bin/mjml --version #env: node: …
```
=> Allow bun to run without Node.js (standalone)

lib/mjml.rb
Resolves: https://github.com/sighmon/mjml-rails/issues/134
This MR prioritizes the `mrml` binary when finding a valid mjml/mrml binary.
At startup, the library searches for all kinds of binaries to find a valid mjml/mrml binary. When use_mrml is set to true, that search is not necessary, and can even be wrong when another dependency introduces mjml somewhere in the path.
In our specific case, we have monitors whenever a process attempts to execute a command as root, which happens here: https://github.com/sighmon/mjml-rails/blob/master/lib/mjml.rb#L111
All of the above could be avoided if the check_for_mrml_binary happens at the top of the chain. It's pretty clear that whenever use_mrml is true, and when check_for_mrml_binary succeeds, we've found a valid MJML/MRML binary.
=> Prioritize mrml binary

README.md, lib/generators/mjml/install/install_generator.rb, lib/generators/mjml/install/templates/mjml.rb, lib/mjml.rb, lib/mjml/cache.rb, lib/mjml/handler.rb, lib/mjml/parser.rb, test/parser_test.rb, test/views/test_template.mjml
**Problem**
Currently, MJML templates are compiled every time a mailer is called, which significantly slows down test execution. This can impact overall performance, especially in test suites with frequent mailer calls.
**Proposed Solution**
This PR introduces caching for compiled MJML templates, leveraging the fact that mailer templates typically do not change frequently. Compiled templates are now cached in `tmp/mjml_cache`, and if a template is modified, it automatically detects the change, recompiles the template, and updates the cache.
**How it Works:**
1. When a mailer is called, if a cache does not exist, the system calculates a unique fingerprint (using SHA256) based on the content of the template file.
2. The next time the mailer is called with the same template, it retrieves the …
=> Improve MJML Mailer Performance by Caching Compiled Templates

lib/mjml/mrml_parser.rb, test/mrml_parser_test.rb
Currently, MRML can't be used in 4.15.0 because the MrmlParser constructor wasn't updated when caching was added.
=> MRML caching

lib/generators/mjml/install/templates/mjml.rb
The `onfig.cache_mjml` setting is duplicated in a generated initializer file. I think L30-32 can be simply removed since that's already declared at L25.
=> Remove duplicated setting in generated template
